name: View Render Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: npm install -g render-cli

      - name: Login to Render
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      - name: Fetch logs from Render
        run: render services logs ${{ secrets.RENDER_SERVICE_ID }} --limit 100
