name: Build and Deploy Pre-Built Image to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering

jobs:
  build-and-deploy:
    name: Build Docker Image and Deploy to Render
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        run: |
          docker build -f server/Dockerfile -t aniflix-server:latest ./server

      - name: Save Docker image as tarball
        run: |
          docker save aniflix-server:latest -o aniflix-server.tar

      - name: Upload Docker image tarball to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cvuef8hr0fns7381f7cg/deploys \
            -H "Authorization: Bearer rnd_bQP2nphNZ83yaaXcI3yGHmTN8BrZ" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":false,"dockerImageTarball":"@aniflix-server.tar"}'
