name: Download JAR File and Save to Build Path

on:
  push:
    branches:
      - main  # Change to the desired branch if needed
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  download_and_save_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR file
      run: |
        # Define the URL for the JAR file and the target path
        FILE_URL="https://github.com/anime-kun32/Aniflix/releases/download/Jar/aniflix.jar"
        TARGET_PATH="server/build/libs/aniflix.jar"
        
        # Download the JAR file
        curl -L -o $TARGET_PATH $FILE_URL

    - name: Commit downloaded file
      run: |
        # Force add the file even though it might be in .gitignore
        git add -f server/build/libs/aniflix.jar
        git commit -m "Add downloaded aniflix.jar file"
        git push
